name: A workflow for my Hello world file
on: push
jobs:
  test:
    name: Test Job
    runs-on: ubunti-latest
    steps:
      - uses: ./test-act
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
